### ISSUE TITLE
Student: Notification about package

### ISSUE THREAD

**Issue by Satloff** [luftdanmark/MailMule#11]
### What I'm trying to achieve (plain english)
Send a rich notification to a student when a package has arrived for them. This should include location, tracking number, and size. 

### As a...
Student

### I want...
to receive rich notifications about my package arrival

### So that...
I know what packages have arrived

(Does finished issue complete this checklist?)

1. [x] Privileged views and APIs are guarded by proper permission checks.
1. [x] Database queries are optimized and the number of queries is constant.
1. [x] The changes are tested.
1. [x] The code is documented (docstrings, project documentation).

**Comment by luftdanmark** [comment]
We are deciding on one email per package.

**Comment by luftdanmark** [comment]
@Satloff, check this out when you get a chance. It's ready for your design-skills. 
Email clients won't load CSS from other sources, so styling has to be inlined in the HTML. 
If that sounds annoying, check out https://github.com/roverdotcom/django-inlinecss.

**Comment by luftdanmark** [comment]
Went ahead and did the design work myself, as @Satloff was occupied with other issues.
